---
title: "herring_LocalScore"
author: "laura e timm"
date: '2024-10-19'
output: html_document
---

# setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libraries
```{r load_libraries, warning=FALSE, message=FALSE}

packages_needed <- c("plyr", "ggplot2", "tidyverse", "data.table", "RColorBrewer")


for(i in 1:length(packages_needed)){
  if(!(packages_needed[i] %in% installed.packages())){install.packages(packages_needed[i])}
  library(packages_needed[i], character.only = TRUE)
}

```

## specify
```{r project_setup}

BASEDIR <- "C:/Users/laura.timm/Desktop/Clupea_pallasii/" #prev DATADIR
PREFIX <- "CPAL-CHARFULL"

# get doCounts output filenames for each population
#poco (position_counts) files were generated with
# for pop in ...
# do
# paste CPAL-CHARFULL_${pop}_wgph.pos CPAL-CHARFULL_${pop}_wgph.counts > CPAL-CHARFULL_${pop}_wgph.pocoFULL
# cut -f3 --complement CPAL-CHARFULL_${pop}_wgph.pocoFULL > CPAL-CHARFULL_${pop}_wgph.poco
# rm CPAL-CHARFULL_${pop}_wgph.pocoFULL
# gzip CPAL-CHARFULL_${pop}_wgph.counts CPAL-CHARFULL_${pop}_wgph.pos
# done

pop_eBSAI_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_eBSAI_wgph.poco")
pop2_GOA_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_2popGOA_wgph.poco")

pop3_GOA_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_3popGOA_wgph.poco")
pop3_PI_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_3popPI_wgph.poco")

CB_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_CB_wgph.poco")
PM_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_PM_wgph.poco")
TOG_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_TOG_wgph.poco")

COR_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_COR_wgph.poco")
KIU_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_KIU_wgph.poco")
KOK_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_KOK_wgph.poco")
PI_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_PI_wgph.poco")

mtGOA1_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_mtGOA1_wgph.poco") 
mtGOA2_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_mtGOA2_wgph.poco")

ebsaiA_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_ebsaiA_wgph.poco")
ebsaiB_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_ebsaiB_wgph.poco")
ebsaiC_filename <- paste0(BASEDIR, "local_score/", PREFIX, "_ebsaiC_wgph.poco")

```

# define functions

##prep population-specific dfs
```{r prep_pop_df}

prep_df <- function(POP_DF) {
  #set colnames
  colnames(POP_DF) <- c("chrName", "pos", "A", "C", "G", "T")
    
  #change chrName to chr number
  chrom_df <- read.table("C:/Users/laura.timm/Desktop/Clupea_pallasii/CHAR_chrom_metadata.txt", header = TRUE)
  colnames(chrom_df) <- c("chrName", "chr")
  #chrom_df <- transform(chrom_df, chrName = as.character(chrName))

  POP_DF <- left_join(POP_DF, chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    select("chr", everything())
  
  # make values of 0 == NA for each nucleotide
  POP_DF[POP_DF == 0] <- NA
  # create columns for al2 and al2 (al = allele), plus total and sum columns
  POP_DF <- POP_DF %>%
    mutate(check1 = pmax(A, C, G, T, na.rm = TRUE)) %>%
    mutate(check2 = pmin(A, C, G, T, na.rm = TRUE))
  POP_DF$Total <- rowSums(POP_DF[,c("A", "C", "G", "T")], na.rm=TRUE)
  POP_DF$Al_Sum <- rowSums(POP_DF[,c("check1", "check2")], na.rm=TRUE)
  
  # remove triallelic (or monoallelic) by seeing if sum and total don't match
  POP_DF <- POP_DF[-(which(POP_DF$Al_Sum != POP_DF$Total)), ]
  
  # remove tri-/mono-allelic columns
  POP_DF <- POP_DF %>%
    subset(select = -c(check1, check2, Al_Sum))

  POP_DF
}

```


##join dfs
```{r join_dfs_to_compare}

join_dfs <- function(POP1_DF, POP2_DF) {
  count_df <- inner_join(POP1_DF, POP2_DF, by = c("chr", "pos"))

  # first: remove loci with any mismatch of alleles across pops
  count_df <- count_df %>%
    mutate(
      remove = case_when(
        is.na(A.x) != is.na(A.y) ~ "RM",
        is.na(C.x) != is.na(C.y) ~ "RM",
        is.na(G.x) != is.na(G.y) ~ "RM",
        is.na(T.x) != is.na(T.y) ~ "RM",
        TRUE ~ "")) %>%
    filter(remove == "") %>%
    subset(select = -c(remove))
  
  # assign counts for pop1 alleles
  count_df <- count_df %>%
    mutate(al1.x = pmax(A.x, C.x, G.x, T.x, na.rm = TRUE),
           al2.x = pmin(A.x, C.x, G.x, T.x, na.rm = TRUE))
  
  # determine which alleles are max and min
  # have to account for sites where the min and max are the same bc the allele
  # count is equal.
  count_df <- count_df %>%
    mutate(
      N1 = case_when(
        A.x == al1.x ~ "A",
        C.x == al1.x ~ "C",
        G.x == al1.x ~ "G",
        T.x == al1.x ~ "T"),
      N2 = case_when(
        # have to make N2 different than N1 when al1 == al2
        al1.x == al2.x & N1 == "A" & al2.x == C.x ~ "C",
        al1.x == al2.x & N1 == "A" & al2.x == G.x ~ "G",
        al1.x == al2.x & N1 == "A" & al2.x == T.x ~ "T",
        al1.x == al2.x & N1 == "C" & al2.x == G.x ~ "G",
        al1.x == al2.x & N1 == "C" & al2.x == T.x ~ "T",
        al1.x == al2.x & N1 == "G" & al2.x == T.x ~ "T",
        # when al1 != al2
        A.x == al2.x ~ "A",
        C.x == al2.x ~ "C",
        G.x == al2.x ~ "G",
        T.x == al2.x ~ "T"))
  
  # then match pop2 alleles with pop1 alleles & assign count value
  count_df <- count_df %>%
    mutate(
      al1.y = case_when(
        N1 == "A" ~ A.y,
        N1 == "C" ~ C.y,
        N1 == "G" ~ G.y,
        N1 == "T" ~ T.y),
      al2.y = case_when(
        N2 == "A" ~ A.y,
        N2 == "C" ~ C.y,
        N2 == "G" ~ G.y,
        N2 == "T" ~ T.y))
  
  # determine which alleles are max and min for pop2
  # just for visualizing --> not used for any calculation
  count_df <- count_df %>%
    mutate(
      N1_ycheck = case_when(
        A.y == al1.y ~ "A",
        C.y == al1.y ~ "C",
        G.y == al1.y ~ "G",
        T.y == al1.y ~ "T"),
      N2_ycheck = case_when(
        A.y == al2.y ~ "A",
        C.y == al2.y ~ "C",
        G.y == al2.y ~ "G",
        T.y == al2.y ~ "T"))
  
  # checks
  if(nrow(count_df %>% filter(Total.x != al1.x + al2.x)) > 0){
    print(" WARNING! ERROR! ALLELE 1 + ALLELE 2 != TOTAL ALLELE COUNT IN POP 1!")
  }else if(nrow(count_df %>% filter(Total.y != al1.y + al2.y)) > 0){
    print(" WARNING! ERROR! ALLELE 1 + ALLELE 2 != TOTAL ALLELE COUNT IN POP 2!")
  }else if(nrow(count_df %>% filter(N1 == N2)) > 0){
    print(" WARNING! ERROR! SAME ALLELE BEING ACCOUNTED FOR IN POP 1.
            LIKELY BECAUSE THE ALLELE COUNT OF THE MAJOR AND MINOR ARE EQUAL.")
  }
  
  # remove unnecessary columns
  count_df <- count_df %>%
    subset(select = -c(A.x, C.x, G.x, T.x, N1, N2, A.y, C.y, G.y, T.y, N1_ycheck, N2_ycheck))
  
  # remove unnecessary columns for fishers exact test, which will then lead to local score
  fet_df <- count_df %>%
    subset(select = -c(Total.x, Total.y))
  
  # conduct fishers exact test on each row (locus)
  fet_df$pval <- apply(fet_df, 1,
                       function(x){
                         tbl <- matrix(as.numeric(x[3:6]), ncol=2, byrow=T)
                         fisher.test(tbl, alternative="two.sided")$p.value
                         })

  # remove unnecessary columns for local score
  fet_df <- fet_df %>%
    subset(select = -c(al1.x, al2.x, al1.y, al2.y))
  
  fet_df
}

```


```{r prep_2pop}

#set comparison title
comp_title <- "2pop"

#label pops
pop1_id <- "eBSAI"
pop2_id <- "nGOA"

#read in dfs
pop1_df_raw <- read.delim(pop_eBSAI_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(pop2_GOA_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep and join dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw)

#############################################################################################
#eBSAI vs nGOA
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
            sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df, pop2_df)

```



```{r prep_3pop}

#set comparison title
comp_title <- "3pop"

#label pops
pop1_id <- "eBSAI"
pop2_id <- "nGOA"
pop3_id <- "PI"

#read in dfs
pop1_df_raw <- read.delim(pop_eBSAI_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(pop3_GOA_filename, header = TRUE, sep = "\t", row.names = NULL)
pop3_df_raw <- read.delim(pop3_PI_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)
pop3_df <- prep_df(pop3_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw, pop3_df_raw)

#############################################################################################
#eBSAI vs nGOA
  
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#eBSAI vs PI
  
  FET_2pop <- join_dfs(pop1_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#nGOA vs PI
  
  FET_2pop <- join_dfs(pop2_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop2_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df, pop2_df, pop3_df)

```



```{r prep_within_nGOA}

#set comparison title
comp_title <- "nGOA"

#label pops
pop1_id <- "COR"
pop2_id <- "KIU"
pop3_id <- "KOK"
pop4_id <- "PI"

#read dfs
pop1_df_raw <- read.delim(COR_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(KIU_filename, header = TRUE, sep = "\t", row.names = NULL)
pop3_df_raw <- read.delim(KOK_filename, header = TRUE, sep = "\t", row.names = NULL)
pop4_df_raw <- read.delim(PI_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)
pop3_df <- prep_df(pop3_df_raw)
pop4_df <- prep_df(pop4_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw, pop3_df_raw, pop4_df_raw)

#############################################################################################
#COR vs KIU
  
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#COR vs KOK
  
  FET_2pop <- join_dfs(pop1_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#COR vs PI
  
  FET_2pop <- join_dfs(pop1_df, pop4_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop4_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df)

#############################################################################################
#KIU vs KOK
  
  FET_2pop <- join_dfs(pop2_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop2_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#KIU vs PI
  
  FET_2pop <- join_dfs(pop2_df, pop4_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop2_id, "-", pop4_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop2_df)

#############################################################################################
#KOK vs PI
  
  FET_2pop <- join_dfs(pop3_df, pop4_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop3_id, "-", pop4_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop3_df, pop4_df)

```



```{r prep_within_eBSAI_regions}

#set comparison title
comp_title <- "eBSAI"

#label pops
pop1_id <- "CB"
pop2_id <- "PM"
pop3_id <- "TOG"

#read in dfs
pop1_df_raw <- read.delim(CB_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(PM_filename, header = TRUE, sep = "\t", row.names = NULL)
pop3_df_raw <- read.delim(TOG_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)
pop3_df <- prep_df(pop3_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw, pop3_df_raw)

#############################################################################################
#CB vs PM
  
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#CB vs TOG
  
  FET_2pop <- join_dfs(pop1_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#PM vs TOG
  
  FET_2pop <- join_dfs(pop2_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop2_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df, pop2_df, pop3_df)

```



```{r prep_mtclusts_GOA_nucdata}

#set comparison title
comp_title <- "mtGOAnuc"

#label pops
pop1_id <- "GOA1"
pop2_id <- "GOA2"

#read in dfs
pop1_df_raw <- read.delim(mtGOA1_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(mtGOA2_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep and join dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw)

#############################################################################################
#GOA1 vs GOA2
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
            sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df, pop2_df)

```



```{r prep_within_eBSAI_clusters}

#set comparison title
comp_title <- "eBSAIclust"

#label pops
pop1_id <- "A"
pop2_id <- "B"
pop3_id <- "C"

#read in dfs
pop1_df_raw <- read.delim(ebsaiA_filename, header = TRUE, sep = "\t", row.names = NULL)
pop2_df_raw <- read.delim(ebsaiB_filename, header = TRUE, sep = "\t", row.names = NULL)
pop3_df_raw <- read.delim(ebsaiC_filename, header = TRUE, sep = "\t", row.names = NULL)

#prep dfs
pop1_df <- prep_df(pop1_df_raw)
pop2_df <- prep_df(pop2_df_raw)
pop3_df <- prep_df(pop3_df_raw)

#remove raw_dfs
rm(pop1_df_raw, pop2_df_raw, pop3_df_raw)

#############################################################################################
#A vs B
  
  FET_2pop <- join_dfs(pop1_df, pop2_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop2_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#A vs C
  
  FET_2pop <- join_dfs(pop1_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop1_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

#############################################################################################
#B vs C
  
  FET_2pop <- join_dfs(pop2_df, pop3_df)
  write.table(FET_2pop, file = paste0(BASEDIR, "local_score/", comp_title, "_", pop2_id, "-", pop3_id, "_localscore_input.txt"),
              sep = "\t", row.names = FALSE, col.names = TRUE)

rm(pop1_df, pop2_df, pop3_df)

```
